fun main() {
    //Class.forName("org.sqlite.JDBC") Может пригодиться для использования sql
    val host = Host()
    host.init(2, 3, "Dan")
    host.printEl()
    val earth = EarthAnimals()
    earth.init(123, "Russia", "middle")
    earth.printEl()
    val bird = Birds()
    bird.init(23, 1200, "Cold")
    bird.init(1, 1200, "Warm")
    bird.printEl()
    val client = Client()
    client.printOptions()
    client.sqlRequest("DROP TABLE Host", 1)
    client.init(1)
    val initiz = Initialization()
    initiz.printOptions()
    initiz.delete(1)
    val service = Service()
    service.findElById(123, "EarthAnimals")
    service.findElWithConditionId(">2", "Host")
    service.groupBy("height", "Birds")
    service.sortByReverse("animalId", "Birds")

}