fun main() {
    val queue = Queue<Int>()
    queue.enqueue(1)
    queue.enqueue(2)
    queue.enqueue(3)
    queue.enqueue(4)
    queue.enqueue(5)
    println(queue.dequeue())
    println(queue.dequeue())
    queue.enqueue(6)
    queue.enqueue(7)
    queue.lis()
    val stack = Stack<Int>()
    stack.push(1)
    stack.push(2)
    stack.push(3)
    stack.push(4)
    println(stack.pop())
    println(stack.pop())
    stack.push(5)
    stack.lis()
}